// AUTO-GENERATED by scripts/generate-doc-topics.ts — do not edit by hand.
// Regenerate with `pnpm gen:doc-topics` whenever content/docs changes.

export type DocLocale = 'en' | 'pt-br';

export interface DocTopic {
  slug: string;
  title: string;
  url: string;
  summary: string;
  excerpt: string;
}

export const DOC_TOPICS: Record<DocLocale, DocTopic[]> = {
  "en": [
    {
      "slug": "marketplace",
      "title": "Marketplace",
      "url": "/docs/marketplace/",
      "summary": "Notes on the plugins marketplace — how the catalog is stored and how to contribute to it.",
      "excerpt": "Notes on the [plugins marketplace](/marketplace) — how the catalog is stored and\nhow to contribute to it.\n\n- **[Adding a marketplace entry](/docs/marketplace/adding-an-entry)**"
    },
    {
      "slug": "marketplace/adding-an-entry",
      "title": "Adding a marketplace entry",
      "url": "/docs/marketplace/adding-an-entry/",
      "summary": "The marketplace catalog is plain JSON in this repo — one file per entry at content/marketplace/<family-dir>/<slug>.json, grouped by family:",
      "excerpt": "The [marketplace](/marketplace) catalog is plain JSON in this repo — one file per\nentry at `content/marketplace/<family-dir>/<slug>.json`, grouped by family:\n\n```\ncontent/marketplace/\n  schema.ts\n  tools/       family: \"tool\"      e.g. tools/issue.json\n  channels/    family: \"channel\"   e.g. channels/telegram.json\n  skills/      family: \"skill\"     e.g. skills/weather.json\n  mcps/        family: \"mcp\"       e.g. mcps/coredash.json\n```\n\nNo build step, no database.\n\n## Steps…"
    },
    {
      "slug": "getting-started",
      "title": "Getting Started",
      "url": "/docs/getting-started/",
      "summary": "Koris Bot is an autonomous AI-agent framework written in TypeScript. It receives messages through pluggable channels (Telegram, WhatsApp, a terminal UI, and a…",
      "excerpt": "Koris Bot is an autonomous AI-agent framework written in TypeScript. It receives messages\nthrough pluggable channels (Telegram, WhatsApp, a terminal UI, and a web dashboard),\nruns them through an LLM, and can execute tools on your behalf. State lives in a local\nSQLite database, so memory and sessions persist across restarts.\n\n## Requirements\n\n- Node.js >= 24\n- `pnpm` — the repo is a single-package pnpm workspace. Never use `npm` or `yarn`.\n\n## Install and run…"
    },
    {
      "slug": "concepts",
      "title": "Concepts",
      "url": "/docs/concepts/",
      "summary": "How a message becomes a reply in Koris Bot, and the pieces that keep state between messages.",
      "excerpt": "How a message becomes a reply in Koris Bot, and the pieces that keep state between messages.\n\n## Message flow\n\n1. A channel plugin (Telegram, WhatsApp, or the TUI) receives a message, normalizes it into\n   an `InboundChannelMessage`, and hands it to the generic `IChannelHandler`. That handler\n   applies the channel rules — group-mention filter, trust-based gating of tools and learned\n   skills, prompt prefixing, reply splitting — then calls `MessageGateway.handle`.\n2. `MessageGateway` resolves the session for the sender, checks whether the message is a slash\n   command, and otherwise…"
    },
    {
      "slug": "channels",
      "title": "Channels",
      "url": "/docs/channels/",
      "summary": "A channel is a message entry point. Koris Bot runs the same agent behind every channel; the channel plugin only handles transport and normalisation.",
      "excerpt": "A channel is a message entry point. Koris Bot runs the same agent behind every channel;\nthe channel plugin only handles transport and normalisation.\n\n## How a message enters\n\nA channel plugin receives a raw message from its platform, normalises it into an\n`InboundChannelMessage`, and delegates to the generic `IChannelHandler`. The handler\napplies the channel rules — group-mention filter, trust-based gating of tools and\nlearned skills, prompt prefixing, reply splitting — and then calls\n`MessageGateway.handle`. From there the flow is identical regardless of channel.…"
    },
    {
      "slug": "ai-providers",
      "title": "AI Providers",
      "url": "/docs/ai-providers/",
      "summary": "Koris Bot talks to language models through a small set of provider implementations. You pick which provider serves each role in koris.json; the framework…",
      "excerpt": "Koris Bot talks to language models through a small set of provider implementations. You pick\nwhich provider serves each role in `koris.json`; the framework resolves the model, context\nwindow, and credentials from there.\n\n## Available providers\n\n- **Ollama** — native client against a local `/api/chat` endpoint. Sends the context window\n  as `options.num_ctx`.\n- **Mock** — an echo provider used for tests. It is forced automatically under Vitest and is\n  the fallback when a provider name is not recognised.\n- **OpenAI-compatible** — one generic Chat Completions client parameterised by a preset.…"
    },
    {
      "slug": "tools",
      "title": "Tools",
      "url": "/docs/tools/",
      "summary": "Tools are the AI agent's capabilities — the actions it can take beyond replying with text. Each one is a plugin under plugins/tools/, one folder per tool, and…",
      "excerpt": "Tools are the AI agent's capabilities — the actions it can take beyond replying with\ntext. Each one is a [plugin](/docs/plugins) under `plugins/tools/`, one folder per tool,\nand each folder owns its own LLM-facing schema, its handler, and the rules for when it\nis offered.\n\n## How a tool call runs\n\nAt boot the framework scans `plugins/tools/`, collects every `ToolDefinition`, and\nstores the list in `ToolPluginsSingleton`. When the model emits a tool call,\n`AgnosticExecutionTool` matches the call's name against that list and runs the matching\ndefinition's `handler`.…"
    },
    {
      "slug": "skills",
      "title": "Skills",
      "url": "/docs/skills/",
      "summary": "A skill is a Markdown file that teaches the agent how to handle a particular kind of request. Skills are instructions, not code — when a skill is active, its…",
      "excerpt": "A skill is a Markdown file that teaches the agent how to handle a particular kind of request.\nSkills are instructions, not code — when a skill is active, its body is folded into the\nagent's context so the model knows what to do. Contrast this with [tools](/docs/tools), which\nare executable handlers the model calls.\n\n## Anatomy\n\nEach skill is a folder under `plugins/skills/` containing a `SKILL.md`:\n\n```\nplugins/skills/\n  weather/\n    SKILL.md\n```\n\n`SKILL.md` has YAML front-matter with `name` and `description`, followed by a body of\ninstructions:…"
    },
    {
      "slug": "plugins",
      "title": "Plugins",
      "url": "/docs/plugins/",
      "summary": "Plugins are how you extend Koris Bot without touching its core. There are three plugin families — channels, tools, and MCP servers — that share the same shape…",
      "excerpt": "Plugins are how you extend Koris Bot without touching its core. There are three plugin\nfamilies — [channels](/docs/channels), [tools](/docs/tools), and [MCP servers](/docs/mcps) —\nthat share the same shape and the same kernel, described below. `plugins/` also holds\n[skills](/docs/skills), but skills are a different kind of extension — plain Markdown,\nsynced by `SkillSyncService` rather than the kernel this page describes.\n\n## The kernel…"
    },
    {
      "slug": "mcps",
      "title": "MCP Servers",
      "url": "/docs/mcps/",
      "summary": "MCP (Model Context Protocol) server plugins allow Koris Bot to connect to external tool ecosystems and dashboards over Streamable HTTP without modifying core…",
      "excerpt": "MCP (Model Context Protocol) server plugins allow Koris Bot to connect to external\ntool ecosystems and dashboards over Streamable HTTP without modifying core code.\nEach integration is a [plugin](/docs/plugins) under `plugins/mcps/`, structured as\na standalone folder.\n\n## How Koris Bot connects to an MCP server\n\nAt startup, Koris Bot scans `plugins/mcps/` for installed server plugins. Each plugin\nregisters a server descriptor on the `MCP_SERVERS` extension point.\n\nWhen an MCP server is enabled:…"
    },
    {
      "slug": "commands",
      "title": "Commands",
      "url": "/docs/commands/",
      "summary": "Slash commands are intercepted by MessageGateway before the message reaches the agent. Recognition, channel completion, and the /help text are all derived from…",
      "excerpt": "Slash commands are intercepted by `MessageGateway` before the message reaches the\nagent. Recognition, channel completion, and the `/help` text are all derived from a\nsingle list, `SLASH_COMMANDS` in `core/src/services/commands/registry.ts`, so a\ncommand is added or retired in exactly one place.\n\n## Reference…"
    },
    {
      "slug": "admin-dashboard",
      "title": "Admin Dashboard",
      "url": "/docs/admin-dashboard/",
      "summary": "Koris Bot ships a browser dashboard for chatting with the agent and managing its configuration.",
      "excerpt": "Koris Bot ships a browser dashboard for chatting with the agent and managing its configuration.\n\n## What serves it\n\nThe UI is a React 19 single-page app (Vite, React Router, Tailwind) in `apps/web/`. The server\nside is an Express app in `core/src/dashboard/` listening on port 3000; it serves the built\nbundle from `dist-web/` and falls back to `index.html` for any unmatched route so the SPA owns\nrouting. Opening `/` redirects to `/admin`, which lands on the chat view.\n\n## Navigation\n\nThe left nav links to:…"
    },
    {
      "slug": "security",
      "title": "Security",
      "url": "/docs/security/",
      "summary": "Koris Bot runs on your own infrastructure and talks to untrusted people over public channels. The controls below limit what the agent can reach and who can…",
      "excerpt": "Koris Bot runs on your own infrastructure and talks to untrusted people over public\nchannels. The controls below limit what the agent can reach and who can drive it.\n\n## Domain allowlist gate\n\nTools that reach the network — `curl_request`, `read_url` and `search_engine` — are\nchecked against an allowlist before they run. The allowlist is `allowed_domains` in\n`koris.json`. A request to a host that is not on the list returns an error string\ninstead of running; an empty allowlist blocks all such requests.…"
    }
  ],
  "pt-br": [
    {
      "slug": "marketplace",
      "title": "Marketplace",
      "url": "/pt-br/docs/marketplace/",
      "summary": "Notas sobre o marketplace de plugins — como o catálogo é armazenado e como contribuir com ele.",
      "excerpt": "Notas sobre o [marketplace de plugins](/pt-br/marketplace) — como o catálogo é\narmazenado e como contribuir com ele.\n\n- **[Adicionando uma entrada no marketplace](/pt-br/docs/marketplace/adding-an-entry)**"
    },
    {
      "slug": "marketplace/adding-an-entry",
      "title": "Adicionando uma entrada no marketplace",
      "url": "/pt-br/docs/marketplace/adding-an-entry/",
      "summary": "O catálogo do marketplace é JSON puro neste repositório — um arquivo por entrada em content/marketplace/<pasta-da-família>/<slug>.json, agrupado por família:",
      "excerpt": "O catálogo do [marketplace](/pt-br/marketplace) é JSON puro neste repositório — um\narquivo por entrada em `content/marketplace/<pasta-da-família>/<slug>.json`, agrupado por\nfamília:\n\n```\ncontent/marketplace/\n  schema.ts\n  tools/       family: \"tool\"      ex.: tools/issue.json\n  channels/    family: \"channel\"   ex.: channels/telegram.json\n  skills/      family: \"skill\"     ex.: skills/weather.json\n  mcps/        family: \"mcp\"       ex.: mcps/coredash.json\n```\n\nSem etapa de build, sem banco de dados.\n\n## Passos…"
    },
    {
      "slug": "getting-started",
      "title": "Primeiros passos",
      "url": "/pt-br/docs/getting-started/",
      "summary": "O Koris Bot é um framework de agente de IA autônomo escrito em TypeScript. Ele recebe mensagens por canais plugáveis (Telegram, WhatsApp, uma interface de…",
      "excerpt": "O Koris Bot é um framework de agente de IA autônomo escrito em TypeScript. Ele recebe\nmensagens por canais plugáveis (Telegram, WhatsApp, uma interface de terminal e um\ndashboard web), processa cada uma com um LLM e pode executar ferramentas em seu nome.\nO estado fica em um banco SQLite local, então memória e sessões sobrevivem a\nreinicializações.\n\n## Requisitos\n\n- Node.js >= 24\n- `pnpm` — o repositório é um workspace pnpm de pacote único. Nunca use `npm` ou `yarn`.\n\n## Instalação e execução…"
    },
    {
      "slug": "concepts",
      "title": "Conceitos",
      "url": "/pt-br/docs/concepts/",
      "summary": "Como uma mensagem vira uma resposta no Koris Bot, e as peças que mantêm o estado entre uma mensagem e outra.",
      "excerpt": "Como uma mensagem vira uma resposta no Koris Bot, e as peças que mantêm o estado entre uma\nmensagem e outra.\n\n## Fluxo de mensagens\n\n1. Um plugin de canal (Telegram, WhatsApp ou a TUI) recebe uma mensagem, normaliza para\n   um `InboundChannelMessage` e entrega ao `IChannelHandler` genérico. Esse handler\n   aplica as regras do canal — filtro de menção em grupo, liberação de ferramentas e\n   skills aprendidas conforme a confiança, prefixo de prompt, divisão de respostas — e\n   então chama `MessageGateway.handle`.\n2. O `MessageGateway` resolve a sessão do remetente, verifica se a mensagem é um…"
    },
    {
      "slug": "channels",
      "title": "Canais",
      "url": "/pt-br/docs/channels/",
      "summary": "Um canal é um ponto de entrada de mensagens. O Koris Bot roda o mesmo agente por trás de todos os canais; o plugin de canal cuida apenas do transporte e da…",
      "excerpt": "Um canal é um ponto de entrada de mensagens. O Koris Bot roda o mesmo agente por trás de\ntodos os canais; o plugin de canal cuida apenas do transporte e da normalização.\n\n## Como uma mensagem entra\n\nO plugin de canal recebe uma mensagem bruta da sua plataforma, normaliza para um\n`InboundChannelMessage` e delega ao `IChannelHandler` genérico. O handler aplica as\nregras do canal — filtro de menção em grupo, liberação de ferramentas e skills conforme\na confiança, prefixo de prompt, divisão de respostas — e então chama\n`MessageGateway.handle`. Daí em diante o fluxo é idêntico, seja qual for o…"
    },
    {
      "slug": "ai-providers",
      "title": "Provedores de IA",
      "url": "/pt-br/docs/ai-providers/",
      "summary": "O Koris Bot conversa com modelos de linguagem por um pequeno conjunto de implementações de provedor. Você escolhe qual provedor atende cada papel no koris.json;…",
      "excerpt": "O Koris Bot conversa com modelos de linguagem por um pequeno conjunto de implementações de\nprovedor. Você escolhe qual provedor atende cada papel no `koris.json`; o framework\nresolve a partir daí o modelo, a janela de contexto e as credenciais.\n\n## Provedores disponíveis\n\n- **Ollama** — cliente nativo contra um endpoint `/api/chat` local. Envia a janela de\n  contexto como `options.num_ctx`.\n- **Mock** — um provedor de eco usado em testes. É forçado automaticamente sob o Vitest e\n  é o fallback quando o nome do provedor não é reconhecido.\n- **Compatível com OpenAI** — um cliente genérico de…"
    },
    {
      "slug": "tools",
      "title": "Ferramentas",
      "url": "/pt-br/docs/tools/",
      "summary": "Ferramentas são as capacidades do agente de IA — as ações que ele pode tomar além de responder com texto. Cada uma é um plugin em plugins/tools/, uma pasta por…",
      "excerpt": "Ferramentas são as capacidades do agente de IA — as ações que ele pode tomar além de\nresponder com texto. Cada uma é um [plugin](/pt-br/docs/plugins) em `plugins/tools/`,\numa pasta por ferramenta, e cada pasta é dona do seu próprio schema exposto ao LLM, do\nseu handler e das regras de quando ela é oferecida.\n\n## Como uma chamada de ferramenta acontece…"
    },
    {
      "slug": "skills",
      "title": "Skills",
      "url": "/pt-br/docs/skills/",
      "summary": "Uma skill é um arquivo Markdown que ensina o agente a lidar com um tipo específico de pedido. Skills são instruções, não código — quando uma skill está ativa,…",
      "excerpt": "Uma skill é um arquivo Markdown que ensina o agente a lidar com um tipo específico de\npedido. Skills são instruções, não código — quando uma skill está ativa, seu conteúdo é\nincorporado ao contexto do agente para que o modelo saiba o que fazer. Compare com as\n[ferramentas](/pt-br/docs/tools), que são handlers executáveis que o modelo chama.\n\n## Anatomia\n\nCada skill é uma pasta em `plugins/skills/` contendo um `SKILL.md`:\n\n```\nplugins/skills/\n  weather/\n    SKILL.md\n```\n\nO `SKILL.md` tem front-matter YAML com `name` e `description`, seguido de um corpo de\ninstruções:…"
    },
    {
      "slug": "plugins",
      "title": "Plugins",
      "url": "/pt-br/docs/plugins/",
      "summary": "Plugins são a forma de estender o Koris Bot sem tocar no core. Há três famílias de plugin — canais, ferramentas e servidores MCP — que compartilham o mesmo…",
      "excerpt": "Plugins são a forma de estender o Koris Bot sem tocar no core. Há três famílias de plugin —\n[canais](/pt-br/docs/channels), [ferramentas](/pt-br/docs/tools) e [servidores MCP](/pt-br/docs/mcps) —\nque compartilham o mesmo formato e o mesmo kernel, descritos abaixo. A pasta `plugins/` também abriga\n[skills](/pt-br/docs/skills), mas skills são um tipo diferente de extensão: Markdown\npuro, sincronizado pelo `SkillSyncService` em vez do kernel descrito nesta página.\n\n## O kernel…"
    },
    {
      "slug": "mcps",
      "title": "Servidores MCP",
      "url": "/pt-br/docs/mcps/",
      "summary": "Plugins de servidores MCP (Model Context Protocol) permitem que o Koris Bot se conecte a ecossistemas externos de ferramentas e dashboards via Streamable HTTP,…",
      "excerpt": "Plugins de servidores MCP (Model Context Protocol) permitem que o Koris Bot se conecte\na ecossistemas externos de ferramentas e dashboards via Streamable HTTP, sem tocar\nno código do core. Cada integração é um [plugin](/pt-br/docs/plugins) em\n`plugins/mcps/`, estruturado em uma pasta independente.\n\n## Como o Koris Bot se conecta a um servidor MCP\n\nNa inicialização, o Koris Bot varre `plugins/mcps/` em busca de plugins de servidores\ninstalados. Cada plugin registra uma definição no ponto de extensão `MCP_SERVERS`.\n\nQuando um servidor MCP está ativado:…"
    },
    {
      "slug": "commands",
      "title": "Comandos",
      "url": "/pt-br/docs/commands/",
      "summary": "Comandos de barra são interceptados pelo MessageGateway antes de a mensagem chegar ao agente. O reconhecimento, o preenchimento por canal e o texto do /help são…",
      "excerpt": "Comandos de barra são interceptados pelo `MessageGateway` antes de a mensagem chegar ao\nagente. O reconhecimento, o preenchimento por canal e o texto do `/help` são todos\nderivados de uma única lista, `SLASH_COMMANDS` em\n`core/src/services/commands/registry.ts`, de modo que um comando é adicionado ou\naposentado em exatamente um lugar.\n\n## Referência…"
    },
    {
      "slug": "admin-dashboard",
      "title": "Dashboard administrativo",
      "url": "/pt-br/docs/admin-dashboard/",
      "summary": "O Koris Bot inclui um dashboard no navegador para conversar com o agente e gerenciar sua configuração.",
      "excerpt": "O Koris Bot inclui um dashboard no navegador para conversar com o agente e gerenciar sua\nconfiguração.\n\n## O que o serve\n\nA interface é uma SPA em React 19 (Vite, React Router, Tailwind) em `apps/web/`. O lado\nservidor é um app Express em `core/src/dashboard/` escutando na porta 3000; ele serve o\nbundle compilado de `dist-web/` e recorre ao `index.html` em qualquer rota não\nreconhecida, de modo que o roteamento fica com a SPA. Abrir `/` redireciona para\n`/admin`, que cai na visão de conversa.\n\n## Navegação\n\nO menu à esquerda leva a:…"
    },
    {
      "slug": "security",
      "title": "Segurança",
      "url": "/pt-br/docs/security/",
      "summary": "O Koris Bot roda na sua própria infraestrutura e conversa com pessoas não confiáveis por canais públicos. Os controles abaixo limitam o que o agente alcança e…",
      "excerpt": "O Koris Bot roda na sua própria infraestrutura e conversa com pessoas não confiáveis por\ncanais públicos. Os controles abaixo limitam o que o agente alcança e quem pode conduzi-lo.\n\n## Lista de domínios permitidos\n\nFerramentas que acessam a rede — `curl_request`, `read_url` e `search_engine` — são\nverificadas contra uma lista de permissões antes de executar. A lista é o\n`allowed_domains` no `koris.json`. Uma requisição a um host fora da lista devolve uma\nmensagem de erro em vez de executar; uma lista vazia bloqueia todas essas requisições.…"
    }
  ]
};
