import { mkdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { getDoc, getDocsTree, summarize, type DocNode } from '../src/lib/docs';
import { LOCALES, localePath, type Locale } from '../src/i18n/locales';

/**
 * Bakes the docs tree into a static topic index that the Cloudflare Worker
 * (`worker/src/index.ts`) evaluates with Jev. The Worker owns the question
 * template, so the public endpoint can only route over these fixed topics —
 * callers cannot turn your API key into a general-purpose Jev proxy.
 *
 * Run with `pnpm gen:doc-topics` before deploying the Worker. The output is
 * committed so a Worker deploy is reproducible without rebuilding the site.
 */

export interface DocTopic {
  slug: string;
  title: string;
  url: string;
  summary: string;
  excerpt: string;
}

const OUT_FILE = join(process.cwd(), 'worker', 'src', 'doc-topics.generated.ts');

function flatten(nodes: DocNode[]): DocNode[] {
  return nodes.flatMap((node) => [node, ...flatten(node.children)]);
}

/**
 * The first ~600 characters of a doc body, cut on a paragraph (or word)
 * boundary. The leading H1 is dropped because the widget renders the title
 * separately.
 */
function excerpt(content: string, maxLength = 600): string {
  const body = content.replace(/^\s*#\s+.*(?:\r?\n)+/, '').trim();
  if (body.length <= maxLength) return body;

  const cut = body.slice(0, maxLength);
  const paragraph = cut.lastIndexOf('\n\n');
  const end = paragraph > maxLength * 0.5 ? paragraph : cut.lastIndexOf(' ');
  return `${(end > 0 ? cut.slice(0, end) : cut).trimEnd()}…`;
}

function topicsFor(locale: Locale): DocTopic[] {
  return flatten(getDocsTree(locale))
    .map((node) => {
      const doc = getDoc(node.slug, locale);
      const content = doc?.content ?? '';
      return {
        slug: node.slug.join('/'),
        title: doc?.meta.title ?? node.title,
        url: localePath(locale, `/docs/${node.slug.join('/')}/`),
        summary: summarize(content),
        excerpt: excerpt(content),
      };
    })
    .filter((topic) => topic.slug.length > 0);
}

const data = Object.fromEntries(LOCALES.map((locale) => [locale, topicsFor(locale)])) as Record<Locale, DocTopic[]>;

const banner = `// AUTO-GENERATED by scripts/generate-doc-topics.ts — do not edit by hand.
// Regenerate with \`pnpm gen:doc-topics\` whenever content/docs changes.

export type DocLocale = '${LOCALES.join("' | '")}';

export interface DocTopic {
  slug: string;
  title: string;
  url: string;
  summary: string;
  excerpt: string;
}

export const DOC_TOPICS: Record<DocLocale, DocTopic[]> = ${JSON.stringify(data, null, 2)};
`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, banner, 'utf-8');
console.log(
  `Wrote ${OUT_FILE} (${LOCALES.map((locale) => `${locale}: ${data[locale].length}`).join(', ')} topics)`,
);
